--- 
- 
  connection: local
  gather_facts: false
  hosts: localhost
  tasks: 
    - name: Import VPC Variables
      include_vars: vars/vpc_setup.txt
      
    - name: "Create vprofile VPC Inst"
      ec2_vpc_net: 
        cidr_block: "{{ vpcCidr }}"
        dns_hostnames: true
        dns_support: true
        name: "{{ vpc_name }}"
        region: "{{ region }}"
        state: "{{ state }}"
        tenancy: default
      register: vpcout

    # - debug: 
    #     var: vpcout

    - name: create Public subnet 1 in zone1
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        az: "{{ zone1 }}"
        state: "{{ state }}"
        cidr: "{{ PubSub1Cidr }}"
        map_public: yes
        resource_tags:
          Name: vprofile-pubsub1
      register: pubsub1_out

    - name: create Public subnet 2 in zone2
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        az: "{{ zone2 }}"
        state: "{{ state }}"
        cidr: "{{ PubSub2Cidr }}"
        map_public: yes
        resource_tags:
          Name: vprofile-pubsub2
      register: pubsub2_out

    - name: create Public subnet 3 in zone3
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        az: "{{ zone3 }}"
        state: "{{ state }}"
        cidr: "{{ PubSub3Cidr }}"
        map_public: yes
        resource_tags:
          Name: vprofile-pubsub3
      register: pubsub3_out
  
    - name: create Private subnet 1 in zone1
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        az: "{{ zone1 }}"
        state: "{{ state }}"
        cidr: "{{ PriSub1Cidr }}"
        map_public: yes
        resource_tags:
          Name: vprofile-privsub1
      register: privsub1_out

    - name: create Private subnet 2 in zone1
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        az: "{{ zone1 }}"
        state: "{{ state }}"
        cidr: "{{ PriSub2Cidr }}"
        map_public: yes
        resource_tags:
          Name: vprofile-privsub2
      register: privsub2_out
    
    - name: create Private subnet 3 in zone1
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        az: "{{ zone1 }}"
        state: "{{ state }}"
        cidr: "{{ PriSub3Cidr }}"
        map_public: yes
        resource_tags:
          Name: vprofile-privsub3
      register: privsub3_out

    - name: Internet Gateway setup
      ec2_vpc_igw:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        state: "{{ state }}"
        resource_tags:
          Name: vprofile-IGW
      register: igw_out