--- 
- 
  connection: local
  gather_facts: false
  hosts: localhost
  tasks: 
    - name: Import VPC Variables
      include_vars: vars/vpc_setup.txt
      
    - name: "Create vprofile VPC Inst"
      ec2_vpc_net: 
        cidr_block: "{{ vpcCidr }}"
        dns_hostnames: true
        dns_support: true
        name: "{{ vpc_name }}"
        region: "{{ region }}"
        state: "{{ state }}"
        tenancy: default
      register: vpcout
    - debug: 
        var: vpcout

    - name: create Public subnet 1 in zone1
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        az: "{{ zone1 }}"
        state: "{{ state }}"
        cidr: "{{ PubSub1Cidr }}"
        map_public: yes
        resource_tags:
          Name: vprofile-pubsub1
      register: pubsub1_out


