--- 
- 
  connection: local
  gather_facts: false
  hosts: localhost
  tasks: 
    - 
      include_vars: vars/vpc_setup.txt
      name: "Import VPC Variables"
    - 
      ec2_vpc_net: 
        cidr_block: "{{ vpcCidr }}"
        dns_hostnames: true
        dns_support: true
        name: "{{ vpc_name }}"
        region: "{{ region }}"
        state: "{{ state }}"
        tenancy: default
      name: "Create vprofile VPC Inst"
      register: vpcout