---
- hosts: localhost
  name: Setup Vprofile Stack
  connection: local
  gather_facts: no
  tasks:
  - name: Import VPC setup Variables
    include_vars: vars/vpc-output_vars

  - name: Import Vprofile setup Variables
    include_vars: vars/vprostacksetup

  - name: Import Vpro setup Variables
    include_vars: vars/vpc_setup.txt

  - name: Create vprofile ec2 key
    ec2_key:
      name: vprokey
      region: "{{ region }}"
    register: vprokey_out

  - debug:
      var: vprokey_out

  - name: store login key
    copy:
      content: "{{ keyout.key.private_key }}"
      dest: ./loginkey_vpro.pem
      mode: 0600
    when: vprokey_out.changed