---
- hosts: localhost
  name: Setup Vprofile Stack
  connection: local
  gather_facts: no
  tasks:
  - name: Import VPC setup Variables
    include_vars: vars/vpc-output_vars

  - name: Import Vprofile setup Variables
    include_vars: vars/vprostacksetup

  - name: Import Vpro setup Variables
    include_vars: vars/vpc_setup.txt

  - name: Create vprofile ec2 key
    ec2_key:
      name: vprokey
      region: "{{ region }}"
    register: vprokey_out

  - debug:
      var: vprokey_out

  - name: store login key
    copy:
      content: "{{ keyout.key.private_key }}"
      dest: ./loginkey_vpro.pem
      mode: 0600
    when: vprokey_out.changed

  - name: Create Security Group for Load Balancer
    ec2-group:
     name: vproELB-sg
     description: Allow port 80 from everywhere and all port within sg
     region: "{{ region }}"
     vpc_id: "{{ vpcid }}"
     rules:
       - proto: tcp
         from_port: 80
         to_port: 80
         cidr_ip: 0.0.0.0/0
    register: vproELBSG_out

    - name: Create Security Group for Vprofile Stack
    ec2-group:
     name: vproStack-sg
     description: Allow port 22 from everywhere and all port within sg
     region: "{{ region }}"
     vpc_id: "{{ vpcid }}"
     purge_rules: no
     rules:
       - proto: tcp
         from_port: 80
         to_port: 80
         group_id: "{{ vroELBSG_out.group_id }}"
       - proto: tcp
         from_port: 22
         to_port: 22
         group_id: "{{ BastionSGid }}"
    register: vproStackSG_out
